<?php

namespace App\Constants;


class CatSystemLogConstants
{
    const USER_LOGIN = "USER_LOGIN";
    const USER_LOGOUT = "USER_LOGOUT";
    const FAILED_USER_LOGIN_ATTEMPT = "FAILED_USER_LOGIN_ATTEMPT";

    const USER_CREATED = "NEW_USER_CREATED";
    const USER_UPDATED = "USER_UPDATED";
    const USER_DELETED = "USER_DELETED";

    const ORGANIZATIONAL_UNIT_CREATED = "ORGANIZATIONAL_UNIT_CREATED";
    const ORGANIZATIONAL_UNIT_UPDATED = "ORGANIZATIONAL_UNIT_UPDATED";
    const ORGANIZATIONAL_UNIT_DELETED = "ORGANIZATIONAL_UNIT_DELETED";

    const NEW_SUBJECT_SENT = "NEW_SUBJECT_SENT";
    const NEW_EXTERNAL_SUBJECT_SENT = "NEW_EXTERNAL_SUBJECT_SENT";
    const ASUNTO_AVANZADO = "ASUNTO_AVANZADO";
    const ASUNTO_RESUELTO = "ASUNTO_RESUELTO";
    const ASUNTO_FINALIZADO = "ASUNTO_FINALIZADO";

    const DOCUMENT_CONSULTED = "DOCUMENT_CONSULTED";

}
